spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_dev
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 8081